language: android  # 构建语言

sudo: false  # 开启基于容器的Travis CI任务，让编译效率更高。

notifications:      # 每次构建的时候是否通知，如果不想收到通知邮箱（个人感觉邮件贼烦），那就设置false吧
  email: false

android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-android-support
  - tools
  
before_install:     
 - chmod +x gradlew  # 改变gradlew的访问权限
  
